// <auto-generated />
using System;
using ConsoleGameEntities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleGameEntities.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20250515062847_RemoveExperience")]
    partial class RemoveExperience
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Archetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArchetypeType")
                        .HasColumnType("int");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("AttackMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("DefenseBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("DefenseMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HealthBase")
                        .HasColumnType("int");

                    b.Property<int>("MagicBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("MagicMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("MaxResource")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecoveryGrowth")
                        .HasColumnType("int");

                    b.Property<int>("RecoveryRate")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("ResistanceMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("ResourceMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<decimal>("SpeedMultiplier")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArchetypeId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int?>("EastId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int?>("NorthId")
                        .HasColumnType("int");

                    b.Property<int?>("SouthId")
                        .HasColumnType("int");

                    b.Property<int?>("WestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EastId");

                    b.HasIndex("NorthId");

                    b.HasIndex("SouthId");

                    b.HasIndex("WestId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Monsters.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AggressionLevel")
                        .HasColumnType("int");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<int>("DefensePower")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("MonsterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resistance")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasFilter("[ItemId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.ToTable("Monsters");

                    b.HasDiscriminator<string>("MonsterType").HasValue("Monster");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArchetypeId")
                        .HasColumnType("int");

                    b.Property<int>("Cooldown")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int?>("DamageType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<int>("SkillCategory")
                        .HasColumnType("int");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.HasIndex("MonsterId");

                    b.ToTable("Skills");

                    b.HasDiscriminator<string>("SkillType").HasValue("Skill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Armor", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Items.Item");

                    b.Property<int>("ArmorType")
                        .HasColumnType("int");

                    b.Property<int>("DefensePower")
                        .HasColumnType("int");

                    b.Property<int>("Resistance")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Consumable", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Items.Item");

                    b.Property<int>("ConsumableType")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Valuable", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Items.Item");

                    b.HasDiscriminator().HasValue("Valuable");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Items.Item");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Monsters.BossMonster", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Monsters.Monster");

                    b.HasDiscriminator().HasValue("BossMonster");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Monsters.EliteMonster", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Monsters.Monster");

                    b.HasDiscriminator().HasValue("EliteMonster");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.BossSkill", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Skills.Skill");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BossSkill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.MagicSkill", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Skills.Skill");

                    b.HasDiscriminator().HasValue("MagicSkill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.MartialSkill", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Skills.Skill");

                    b.HasDiscriminator().HasValue("MartialSkill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.SupportSkill", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Skills.Skill");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("StatAffected")
                        .HasColumnType("int");

                    b.Property<int>("SupportEffect")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SupportSkill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.UltimateSkill", b =>
                {
                    b.HasBaseType("ConsoleGameEntities.Models.Skills.Skill");

                    b.HasDiscriminator().HasValue("UltimateSkill");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Inventory", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Entities.Player", "Player")
                        .WithOne("Inventory")
                        .HasForeignKey("ConsoleGameEntities.Models.Entities.Inventory", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Player", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Entities.Archetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "CurrentRoom")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Archetype");

                    b.Navigation("CurrentRoom");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Room", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "East")
                        .WithMany()
                        .HasForeignKey("EastId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "North")
                        .WithMany()
                        .HasForeignKey("NorthId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "South")
                        .WithMany()
                        .HasForeignKey("SouthId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "West")
                        .WithMany()
                        .HasForeignKey("WestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("East");

                    b.Navigation("North");

                    b.Navigation("South");

                    b.Navigation("West");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Item", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Entities.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Monsters.Monster", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Items.Item", "Treasure")
                        .WithOne("Monster")
                        .HasForeignKey("ConsoleGameEntities.Models.Monsters.Monster", "ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsoleGameEntities.Models.Entities.Room", "Room")
                        .WithMany("Monsters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");

                    b.Navigation("Treasure");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Skills.Skill", b =>
                {
                    b.HasOne("ConsoleGameEntities.Models.Entities.Archetype", "Archetype")
                        .WithMany("Skills")
                        .HasForeignKey("ArchetypeId");

                    b.HasOne("ConsoleGameEntities.Models.Monsters.Monster", "Monster")
                        .WithMany("Skills")
                        .HasForeignKey("MonsterId");

                    b.Navigation("Archetype");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Archetype", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Player", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Entities.Room", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Items.Item", b =>
                {
                    b.Navigation("Monster");
                });

            modelBuilder.Entity("ConsoleGameEntities.Models.Monsters.Monster", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
